### ISSUE TITLE
ParseError cinder_docs.sty, unexpected "eos"

### ISSUE THREAD

**Issue by ghost** [gregkepler/Cinder#17]
I'm hitting a strange error running `gulp build` and it looks like something in the `cinder_docs.styl` file is tripping up the build process:

``` sh
 ~/s/C/d/stylesrc 🍔  node_modules/.bin/gulp build
[17:00:16] Using gulpfile ~/sandbox/Cinder/docs/stylesrc/gulpfile.js
[17:00:16] Starting 'styles'...
[17:00:16] Starting 'scripts'...
Potentially unhandled rejection [2] ParseError: /Users/pizthewiz/sandbox/Cinder/docs/stylesrc/stylus/cinder_docs.styl:689:2
   685|     color: white;
   686| }
   687| #nav_search > #search > #search-results > #search-results-view-all a:hover {
   688|     color: #c64b24;
   689| }
---------^

unexpected "eos"

    at Parser.error (/Users/pizthewiz/sandbox/Cinder/docs/stylesrc/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:257:11)
    at Parser.stmt (/Users/pizthewiz/sandbox/Cinder/docs/stylesrc/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:803:32)
    at Parser.statement (/Users/pizthewiz/sandbox/Cinder/docs/stylesrc/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:674:21)
    at Parser.block (/Users/pizthewiz/sandbox/Cinder/docs/stylesrc/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:848:21)
    at Parser.selector (/Users/pizthewiz/sandbox/Cinder/docs/stylesrc/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:1535:24)
    at Parser.stmt (/Users/pizthewiz/sandbox/Cinder/docs/stylesrc/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:767:26)
    at Parser.statement (/Users/pizthewiz/sandbox/Cinder/docs/stylesrc/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:674:21)
    at Parser.parse (/Users/pizthewiz/sandbox/Cinder/docs/stylesrc/node_modules/gulp-stylus/node_modules/stylus/lib/parser.js:234:25)
    at Renderer.render (/Users/pizthewiz/sandbox/Cinder/docs/stylesrc/node_modules/gulp-stylus/node_modules/stylus/lib/renderer.js:80:22)
    at dispatch (/Users/pizthewiz/sandbox/Cinder/docs/stylesrc/node_modules/gulp-stylus/node_modules/accord/node_modules/when/node.js:71:15)
[17:00:16] Finished 'scripts' after 94 ms
 ~/s/C/d/stylesrc 🍔  
```

In case it helps, is my environment info:

``` sh
 ~/s/C/d/stylesrc 🍔  node --version
v0.12.7
 ~/s/C/d/stylesrc 🍔  npm --version
2.13.5
 ~/s/C/d/stylesrc 🍔  npm outdated
Package            Current  Wanted  Latest  Location
gulp-file-include    0.8.0   0.8.0  0.13.7  gulp-file-include
gulp-filter          2.0.2   2.0.2   3.0.0  gulp-filter
gulp-include         1.1.1   1.1.1   2.0.2  gulp-include
gulp-minify-css     0.3.13  0.3.13   1.2.0  gulp-minify-css
gulp-stylus          1.3.7   1.3.7   2.0.6  gulp-stylus
 ~/s/C/d/stylesrc 🍔  
```

**Comment by gregkepler** [comment]
Hi @pizthewiz. Thanks for checking this stuff out.

Looks like it was an issue with how newer versions of gulp-stylus processes comments in .stylus files. It should be fixed in 18c8768b4879b18101a77fb7b82d5ebfb1d59c5e

The fix includes:
- updating the package files so that it's installing specific package versions and removing old junk
- updating how filter is used in the gulp file
- updating some comments in the .styl files

Feel free to reopen if you still have issues.

**Comment by ghost** [comment]
That did the trick, thanks for all your great work on the docs!

**Comment by gregkepler** [comment]
Great, thanks man.
