### ISSUE TITLE
generateDocs on current doxNext failing

### ISSUE THREAD

**Issue by lucasvickers** [gregkepler/Cinder#38]
This is on your current doxNext branch

```
./generateDocs.py
```

...

```
Processing file: xml/classcinder_1_1_capture_impl_direct_show_1_1_device.xml > /Volumes/SCRATCH/lib/cinder/docs/html/classcinder_1_1_capture_impl_direct_show_1_1_device.html
    *** WARNING: [ NO CLASS OBJECT DEFINED FOR: CaptureMgr ] ***
Processing file: xml/classcinder_1_1_capture_mgr.xml > /Volumes/SCRATCH/lib/cinder/docs/html/classcinder_1_1_capture_mgr.html
Traceback (most recent call last):
  File "./generateDocs.py", line 3540, in <module>
    process_dir("xml/", "html/")
  File "./generateDocs.py", line 3380, in process_dir
    process_file(full_path)
  File "./generateDocs.py", line 3363, in process_file
    process_xml_file_definition(in_path, os.path.join(HTML_DEST_PATH, save_path), file_type)
  File "./generateDocs.py", line 1841, in process_xml_file_definition
    file_data = fill_class_content(tree)
  File "./generateDocs.py", line 2046, in fill_class_content
    function_obj = parse_function(bs4, memberFn, class_name)
  File "./generateDocs.py", line 1346, in parse_function
    member_obj = parse_member_definition(bs4, member, member_name)
  File "./generateDocs.py", line 1318, in parse_member_definition
    description_div = markup_description(bs4, member)
  File "./generateDocs.py", line 1576, in markup_description
    markup_brief_description(bs4, tree, description_el)
  File "./generateDocs.py", line 1567, in markup_brief_description
    iterate_markup(bs4, tree.find(r'briefdescription/'), description_el)
  File "./generateDocs.py", line 1547, in iterate_markup
    iterate_markup(bs4, child, current_tag)
  File "./generateDocs.py", line 1540, in iterate_markup
    html_tag = replace_tag(bs4, tree, current_tag, content)
  File "./generateDocs.py", line 1517, in replace_tag
    content = content.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by gregkepler** [comment]
It wasn't failing for me for some reason, so if this didn't fix it, let me know. Stepping away from the computer for a a bit. Good luck.

**Comment by lucasvickers** [comment]
It runs and looks good for my stuff, thanks!
